---
- hosts: tag_type_devops
  vars_prompt:
    - name: account
      prompt: DevOps Account
      private: no

    - name: token
      prompt: Access Token
      private: no

    - name: pool
      prompt: Agent Pool
      private: no

    - name: azuresubid
      prompt: Azure Subscription ID
      private: no

    - name: azureclientid
      prompt: Azure Client ID
      private: no

    - name: azuresecret
      prompt: Azure Client Secret
      private: no

    - name: azuretenant
      prompt: Azure Tenant ID
      private: no

  vars:
    ansible_python_interpreter: "auto"
    user: "{{ ansible_user_id }}"
    setup_devops: true
    setup_standard: true
    setup_docker: true
    setup_ansible: true
    setup_azure: true

  tasks:
    - name: Install and Configure Azure DevOps Agent
      block:
        - name: Create Folder DevOpsAgent
          ansible.builtin.file:
            path: ~/DevOpsAgent
            state: directory

        - name: Download vsts-agent
          ansible.builtin.get_url:
            url: https://vstsagentpackage.azureedge.net/agent/2.190.0/vsts-agent-linux-x64-2.190.0.tar.gz
            dest: ~/DevOpsAgent/vsts-agent-linux-x64-2.190.0.tar.gz

        - name: Extract DevOpsAgent
          ansible.builtin.unarchive:
            src: ~/DevOpsAgent/vsts-agent-linux-x64-2.190.0.tar.gz
            dest: ~/DevOpsAgent
            remote_src: yes

        - name: Check if agent is installed
          stat:
            path: ~/DevOpsAgent/svc.sh
          register: svcfile

        - name: Configure DevOpsAgent
          shell: |
            /home/{{ user }}/DevOpsAgent/config.sh --unattended --url https://dev.azure.com/{{ account }} --auth pat --token {{ token }} --pool {{ pool }}  --acceptTeeEula
          when: not svcfile.stat.exists

        - name: Check if agent service is installed
          stat:
            path: /etc/systemd/system/vsts.agent.{{ account }}.{{ pool }}.{{ ansible_hostname }}.service
          register: servicefile

        - name: Configure DevOpsAgent as a Service
          shell: |
            cd /home/{{ user }}/DevOpsAgent
            ./svc.sh install
          become: yes
          when: not servicefile.stat.exists

        - name: Start vsts agent
          ansible.builtin.systemd:
            name: vsts.agent.{{ account }}.{{ pool }}.{{ ansible_hostname }}.service
            state: started
          become: yes
      when: setup_devops == true

    - name: Install and Configure Standard packages
      block:
        - name: Install Standard packages
          ansible.builtin.apt:
            name:
              - zip
              - unzip
            state: present
            update_cache: yes
          become: yes
      when: setup_standard == true

    - name: Install and Configure Ansible
      block:
        - name: Install packages for Ansible
          ansible.builtin.apt:
            name:
              - python3-pip
              - python3-winrm
            state: present
            update_cache: yes
          become: yes

        - name: Install ansible
          ansible.builtin.pip:
            name: ansible
          #become: yes

        - name: Install Azure requirements for Ansible
          ansible.builtin.pip:
            requirements: "/usr/local/lib/python3.8/dist-packages/ansible_collections/azure/azcollection/requirements-azure.txt"
          #become: yes
      when: setup_ansible == true

    - name: Install and Configure Docker
      block:
        - name: Install packages for docker
          ansible.builtin.apt:
            name:
              - docker.io
            state: present
            update_cache: yes
          become: yes

        - name: Allow User to run docker
          ansible.builtin.user:
            name: "{{ user }}"
            group: docker
          become: yes
      when: setup_docker == true

    - name: Install and Configure Azure
      block:
        - name: Create Folder .azure
          ansible.builtin.file:
            path: ~/.azure
            state: directory

        - name: Add Credential file for Azure
          ansible.builtin.template:
            src: credentials.j2
            dest: ~/.azure/credentials

#        - name: Install packages for azure-cli
#          ansible.builtin.apt:
#            name:
#              - azure-cli
#            state: present
#            update_cache: yes
#          become: yes
      when: setup_azure == true

    - name: Restart DevOpsAgent
      ansible.builtin.reboot:
      become: yes